export enum AppRoute {
  APP = 'APP',
  AUTH = 'AUTH',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  HOME = 'HOME',
  ACCOUNT = 'ACCOUNT',
  PAYMENT = 'PAYMENT',
  ACTIVITIES = 'ACTIVITIES',
  HOME_NAVIGATOR = 'HOME_NAVIGATOR',
  ACCOUNT_NAVIGATOR = 'ACCOUNT_NAVIGATOR',
}
